### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/simpute-py#29] opened 2023-01-23 22:49 UTC
Congratulations on finishing milestone 2!  Nice work on the Tests on Python and setting up your R repo!  Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

Group 11

There isn't an unit test function for each specified function, which is named after the function being tested (e.g., if the function is named foo then the unit test function is named test_foo). For example: test_bool_simpute_py.py for bol_imputer.py- mechanics -5

Some functions aren't passing the unit tests. - accuracy -1 

Ex. 

<img width="917" alt="Screenshot 2023-01-23 at 1 56 29 PM" src="https://user-images.githubusercontent.com/45893111/214168695-b290fc8f-bb39-4c80-b011-dbb456ddfec0.png">

There ins't a paragraph describing where your package fit into the R ecosystem. Are there any other R packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well). - mechanics -2.

The functions are developed using the same branch or there are not meaningful names for the branches . - mechanics -2

Althrun is consistently committing to the GitHub at a low level compared to the other team members in both the R and python repo. Remember to try your best to commit equal amounts. In conclusion, this group did a great job for Milestone 2! Looking forward to seeing how this project develops. 

Ps, this milestone is out of 70

**Comment by LisaSeq** [comment] 2023-01-27 00:30
@andytai7 - Can you clarify what the issue is with "The functions are developed using the same branch or there are not meaningful names for the branches"? We did make an active effort to ensure we each had our own branches and merge request for Milestone 2. Thanks!

**Comment by LisaSeq** [comment] 2023-01-27 00:43
@andytai7 - Also for the point "There isn't an unit test function for each specified function, which is named after the function being tested", is the only issue the one you mentioned with regards to test_bool_simpute_py.py not being called test_bol_imputer.py? Or are there other issues you are asking to be addressed?

**Comment by andytai7** [comment] 2023-01-27 01:56
> @andytai7 - Can you clarify what the issue is with "The functions are developed using the same branch or there are not meaningful names for the branches"? We did make an active effort to ensure we each had our own branches and merge request for Milestone 2. Thanks!

Hi @LisaSeq 
I think that this group deleted the branches before actually submitting the milestones. As a result the TAs can't view which branches was used as what. Next time i would suggest keeping the branches and deleting them after you have submitted your milestone. 

> @andytai7 - Also for the point "There isn't an unit test function for each specified function, which is named after the function being tested", is the only issue the one you mentioned with regards to test_bool_simpute_py.py not being called test_bol_imputer.py? Or are there other issues you are asking to be addressed?

Yes this is what group 11 got marks off for.

**Comment by renee-kwon** [comment] 2023-01-28 03:42
@andytai7 Hi Andy, could we please request a regrade on the branching issue? 
Our team was not aware they should not be deleted after being merged but the commit [history](https://github.com/UBC-MDS/simpute-py/commits/master) shows our use of individual branches with meaningful names as in the milestone instructions.

**Closed as completed** 2023-01-29 14:00 UTC
